### ISSUE TITLE
uploading large(er than test) keys fails with a postgresql error in default setup

### ISSUE THREAD

**Issue by ichdasich** [nomnomtom/keybiz#1]
Heho,
when I try to upload my personal key, i receive the following exception:

OperationalError at /keycheck/manage

index row size 7184 exceeds maximum 2712 for index "keycheck_gpgkey_keydata_0c680c3b_uniq"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.

Request Method:     POST
Request URL:    https://sks.fgsect.de/keycheck/manage
Django Version:     1.9.6
Exception Type:     OperationalError
Exception Value:    

index row size 7184 exceeds maximum 2712 for index "keycheck_gpgkey_keydata_0c680c3b_uniq"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.

Exception Location:     /usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py in execute, line 64
Python Executable:  /usr/local/bin/uwsgi
Python Version:     2.7.9
Python Path:    

['.',
 '',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']

Server time:    Fri, 20 May 2016 12:59:27 +0000

**Comment by nomnomtom** [comment]
This seems to be a 5 year old bug: https://code.djangoproject.com/ticket/14904

I'll try to change that unique constraint to prevent indexing of large keys

**Comment by nomnomtom** [comment]
this should fix it. To apply, replace the file, then go to your keybiz dir and type the following 2 commands:

```
./manage.py makemigrations
./manage.py migrate
```

and reload your wsgi server (e.g. `service apache2 force-reload` or `uwsgi --reload /tmp/keybiz.pid`)

**Comment by ichdasich** [comment]
confirmed working
